name: cutils ci

on: push

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test cutils
        run: make cutils.test
      - name: Test estr
        run: make estr.test
      - name: Test cmder
        run: make cmder.test
      - name: Test all
        run: make test
      - name: Clean
        run: make clean
